### ISSUE TITLE
Can't install because 2.0.0 is not available as a github release

### ISSUE THREAD

**Issue by wasi-master** [a11ce/micro-autofmt#1]
```sh
Downloading "autofmt" (2.0.0) from "https://github.com/a11ce/micro-autofmt/archive/2.0.0.zip"
zip: not a valid zip file
```

repo.json specifies version 2.0.0 [^1] but it is not yet on github as a release [^2]

[^1]: https://github.com/a11ce/micro-autofmt/blob/master/repo.json#L7
[^2]: https://github.com/a11ce/micro-autofmt/releases

**Comment by a11ce** [comment]
Fixed, sorry for the delay.
